# Generated by Django 4.2.7 on 2025-11-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_trip_user_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(choices=[('europe', 'Europe'), ('asia', 'Asia'), ('africa', 'Africa'), ('north_america', 'North America'), ('south_america', 'South America'), ('oceania', 'Oceania'), ('middle_east', 'Middle East')], max_length=50)),
                ('trip_types', models.CharField(max_length=255)),
                ('activities', models.TextField()),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('best_time_to_visit', models.CharField(blank=True, max_length=100, null=True)),
                ('average_cost', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
